version: '3.8'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: 3.110.164.144
