version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
